### PR TITLE
Add word AUTOGENERATED to comment block

### PR DESCRIPTION
**Pull request by garvankeeley**
Help so make it clear that local changes to these files will be overwritten.
I almost make this mistake. Of course, I didn't read the comment block at all :), but if I did skim it, this would have alerted me.

### CODE REVIEW

**Comment by garvankeeley** [comment]
Forgot to bump build number, and npm build. Will do...

**Review by bwinton — CHANGES_REQUESTED** [review]
May as well add it to the gimp and libreoffice versions while we're here… 🙂

**Comment by garvankeeley** [comment]
@bwinton how now brown cow?

**Review by bwinton — APPROVED** [review]
LGTM!

**Comment by garvankeeley** [comment]
Sorry, forgot to bump the version. Is just comment change though, so probably ok.

**Comment by bwinton** [comment]
No worries. I probably won't release it until we get some more stuff in there…

**Comment by aminalhazwani** [comment]
For the next releases let's remember to update the `CHANGELOG.md` as well, thank you very much for your contribution!

**Pull request merged**
