### PR TITLE
Add more alpha colors to be used with the 'input' spec

### PR DESCRIPTION
**Pull request by julienw**
I used https://design.firefox.com/photon/components/input-fields.html as source of truth.

### CODE REVIEW

**Review by bwinton — APPROVED** [review]
Looks good to me. Thanks!

**Comment by julienw** [comment]
Thanks @bwinton :) Do you think you'll be able to ship a new release soon?

**Comment by bwinton** [comment]
Hmmm… Good question. I feel like there are some more alpha-versions of colours coming out of the DevTools spec work. Do you know if those are all in yet?

**Comment by julienw** [comment]
Ah I have no idea, I'm not part of the devtools team these days :)

**Comment by julienw** [comment]
Hey @bwinton, this PR is still the latest PR merged, maybe we could have a release after all? ;)

**Comment by bwinton** [comment]
Yeah, sure. Sounds like a plan. 🙂

**Comment by bwinton** [comment]
https://www.npmjs.com/package/photon-colors/v/3.3.2 is up now!

**Pull request merged**
